config/routes.rb
Rails.application.routes.draw do
  resources :banks
  get 'reports/sales_report'
  get 'reports/transfers_report'
  resources :product_discounts
  resources :manger_discounts
  get 'session/login'
  post 'session/attempt_login'
  get 'session/logout'
  resources :bank_transfers
  resources :sales_operations do
    collection do
      post :import
    end
  end
  resources :mangers
  resources :assistants
  resources :external_employees
  resources :external_transfers
  resources :marketers
  resources :deliveries
  resources :delegates
  resource  :home,                      only: [:index]
  root 'home#index'
  resources :users, except: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/manger.rb
# == Schema Information
#
# Table name: mangers
#
#  id                   :bigint(8)        not null, primary key
#  city                 :string
#  final_manager_amount :float            default(0.0), not null
#  for_him              :float
#  name                 :string
#  phone_NO             :string
#  to_him               :float
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  country_id           :bigint(8)
#
# Indexes
#
#  index_mangers_on_country_id  (country_id)
#
# Foreign Keys
#
#  fk_rails_...  (country_id => countries.id)
#

class Manger < ApplicationRecord

  # Associations
  has_many :deliveries, dependent: :destroy, inverse_of: :manger
  has_many :sales_operations, dependent: :destroy, inverse_of: :manger
  has_many :manger_discounts, dependent: :destroy, inverse_of: :manger
  belongs_to :country

  # Validations
  validates :name,  presence: true

  # Callback
  before_create :default_one_account
  before_destroy :not_deletable


  private

  def default_one_account
    errors.add(:base, 'لايمكن اضافة حساب اخر') and throw(:abort) if Manger.where(country_id: self.country_id).any?
  end

  def not_deletable
    errors.add(:base, 'لايمكنك حذف المدير الافتراضي') 
    throw(:abort) 
  end
end

app/controllers/mangers_controller.rb
class MangersController < ApplicationController
  before_action :set_manger, only: [:show, :edit, :update, :destroy]

  # GET /mangers
  # GET /mangers.json
  def index
    @mangers = @current_country.mangers.page(params[:page])

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'Manger',
               layout: 'pdf'
      end
    end
  end

  # GET /mangers/1
  # GET /mangers/1.json
  def show
  end

  # GET /mangers/new
  def new
    @manger = @current_country.mangers.new
  end

  # GET /mangers/1/edit
  def edit
  end

  # POST /mangers
  # POST /mangers.json
  def create
    @manger = @current_country.mangers.new(manger_params)

    respond_to do |format|
      if @manger.save
        format.html { redirect_to mangers_url, notice: 'تمت عملية الاضافة بنجاح' }
        format.json { render :show, status: :created, location: @manger }
      else
        format.html { render :new }
        format.json { render json: @manger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mangers/1
  # PATCH/PUT /mangers/1.json
  def update
    respond_to do |format|
      if @manger.update(manger_params)
        format.html { redirect_to mangers_url, notice: 'تمت عملية التعديل بنجاح' }
        format.json { render :show, status: :ok, location: @manger }
      else
        format.html { render :edit }
        format.json { render json: @manger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mangers/1
  # DELETE /mangers/1.json
  def destroy
    respond_to do |format|
      if @manger.destroy
        format.html { redirect_to mangers_url, notice: 'تمت عملية الحذف بنجاح' }
        format.json { head :no_content }
      else
        format.html { redirect_to mangers_url, notice: @manger.errors.full_messages.first }
        format.json { render json: @manger.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manger
      @manger = current_country.mangers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manger_params
      params.require(:manger).permit(:name, :password, :role_type, :city, :phone_NO, :for_him, :to_him, :final_manager_amount)
    end
end

app/helpers/mangers_helper.rb
module MangersHelper
end

app/views/mangers/_form.html.erb
<div  class="form-group">
  <%= form_with(model: manger, local: true) do |form| %>
    <% if manger.errors.any? %>
      <div  class="alert alert-warning" role="alert" style="text-align: center;" >
        <h3> يرجئ التاكد من التالي </h3>
        <ul style="list-style-type: none;">
        <% manger.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label 'الاسم', style: "text-align: right; float: right" %>
      <%= form.text_field :name, class: "form-control" , placeholder: "الاسم"  %>
    </div>

    <div class="form-group">
      <%= form.label 'المدينه', style: "text-align: right; float: right" %>
      <%= form.text_field :city, class: "form-control" , placeholder: "المدينه" %>
    </div>

    <div class="form-group">
      <%= form.label 'رقم الجوال', style: "text-align: right; float: right" %>
      <%= form.text_field :phone_NO, class: "form-control" , placeholder:"رقم الجوال" %>
    </div>

    <div class="form-group">
      <%= form.label 'اجمالي نصيب المدير ', style: "text-align: right; float: right" %>
      <%= form.number_field :final_manager_amount, step: :any, class: "form-control", placeholder:"الرصيد الافتراضي" %>
    </div>

    <div class="form-group">
      <%= form.label 'رصيد الاداره ', style: "text-align: right; float: right" %>
      <%= form.number_field :for_him, step: :any, class: "form-control", placeholder:"الرصيد الافتراضي" %>
    </div>

    <div class="form-group">
      <%= form.label 'الرصيد الفعلي', style: "text-align: right; float: right" %>
      <%= form.number_field :to_him, step: :any, class: "form-control", placeholder:"الرصيد الفعلي" %>
    </div>

    <div class="form-group">
      <%= form.submit "موافق",class:"btn btn btn-secondary my-2 my-sm-0" %>
    </div>
  <% end %>
</div>

app/views/mangers/edit.html.erb
<br>
<h2 style="text-align: center;">تعديل بيانات المدير</h2>

<%= render 'form', manger: @manger %>

app/views/mangers/index.html.erb
<br>
<div class="alert alert-info" role="alert" style="text-align: center;">
   اجمالي نصيب المدير  : صافي  المبالغ المستحقه للمدير من عمليات البيع تتاثر بمصروفات المدير فقط
</div>
<div class="alert alert-info" role="alert" style="text-align: center;">
   رصيد الاداره  : صافي  المبالغ المستحقه الاداره (المدير و المساعدين) من عمليات البيع  
</div>
<div class="alert alert-info" role="alert" style="text-align: center;">
   الرصيد الفعلي هي المبالغ التي تم استلمها من المندوبين ناقص مصروفات المدير والتحويلات المرسله 
</div>

<h2 style="text-align: center;">
الاداره ب<%= @current_country.name %> 
</h2>

<div class="table-responsive" >
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>الاسم</th>
        <th>المدينه</th>
        <th>اجمالي نصيب المدير</th>
        <th>رصيد الاداره </th>
        <th>الرصيد الفعلي </th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody style="text-align: center;">
      <% @mangers.each do |manger| %>
        <tr>
          <td><%= manger.name %></td>
          <td><%= manger.city %></td>
          <td><%= manger.final_manager_amount %></td>
          <td><%= manger.for_him %></td>
          <td><%= manger.to_him %></td>
          <td><%= link_to 'تعديل', edit_manger_path(manger), class: "btn btn-light" %></td>
          <td><%= link_to 'حذف', manger, method: :delete, class: "btn btn-light", data: { confirm: 'هل انت متاكد؟' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'إضافة مدير', new_manger_path, class: "btn btn btn-secondary my-2 my-sm-0"%>
<%= link_to "استخراج ملف pdf", mangers_path(format: "pdf"),class: "btn btn btn-secondary my-2 my-sm-0" %>

app/views/mangers/index.pdf.erb
<br>
<div class="alert alert-info" role="alert" style="text-align: center;">
   اجمالي نصيب المدير  : صافي  المبالغ المستحقه للمدير من عمليات البيع تتاثر بمصروفات المدير فقط
</div>
<div class="alert alert-info" role="alert" style="text-align: center;">
   رصيد الاداره  : صافي  المبالغ المستحقه الاداره (المدير و المساعدين) من عمليات البيع  
</div>
<div class="alert alert-info" role="alert" style="text-align: center;">
   الرصيد الفعلي هي المبالغ التي تم استلمها من المندوبين ناقص مصروفات المدير والتحويلات المرسله 
</div>
<br>
<br>

<h2 style="text-align: center;">
الاداره ب<%= @current_country.name %> 
</h2>

<div class="table-responsive" >
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>الاسم</th>
        <th>المدينه</th>
        <th>اجمالي نصيب المدير</th>
        <th>رصيد الاداره </th>
        <th>الرصيد الفعلي </th>
      </tr>
    </thead>

    <tbody style="text-align: center;">
      <% @mangers.each do |manger| %>
        <tr>
          <td><%= manger.name %></td>
          <td><%= manger.city %></td>
          <td><%= manger.final_manager_amount %></td>
          <td><%= manger.for_him %></td>
          <td><%= manger.to_him %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/mangers/new.html.erb
<br>
<h1 style="text-align: center;" >إضافة مدير </h1>

<%= render 'form', manger: @manger %>

<%= link_to 'عوده', mangers_path , class: "btn btn btn-secondary my-2 my-sm-0"%>

app/views/mangers/show.html.erb
<br>
<p id="notice" style="text-align: center;" ><%= notice %></p>

<dl class="row" style="text-align: right;">
  <dt class="col-sm-3">الاسم </dt>
  <dd class="col-sm-9"><%= @manger.name %></dd>
  <dt class="col-sm-3">المدينه </dt>
  <dd class="col-sm-9"><%= @manger.city %></dd>
  <dt class="col-sm-3">رقم الجوال </dt>
  <dd class="col-sm-9"><%= @manger.phone_NO %></dd>
  <dt class="col-sm-3">الرصيد الحالي </dt>
  <dd class="col-sm-9"><%= @manger.for_him %></dd>
</dl>

<%= link_to 'تعديل', edit_manger_path(@manger) , class: "btn btn btn-secondary my-2 my-sm-0"%> |
<%= link_to 'عودة', mangers_path , class: "btn btn btn-secondary my-2 my-sm-0" %>