config/routes.rb
Rails.application.routes.draw do
  resources :banks
  get 'reports/sales_report'
  get 'reports/transfers_report'
  resources :product_discounts
  resources :manger_discounts
  get 'session/login'
  post 'session/attempt_login'
  get 'session/logout'
  resources :bank_transfers
  resources :sales_operations do
    collection do
      post :import
    end
  end
  resources :mangers
  resources :assistants
  resources :external_employees
  resources :external_transfers
  resources :marketers
  resources :deliveries
  resources :delegates
  resource  :home,                      only: [:index]
  root 'home#index'
  resources :users, except: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bank_transfer.rb
# == Schema Information
#
# Table name: bank_transfers
#
#  id               :bigint(8)        not null, primary key
#  date_of_transfer :datetime
#  note             :string
#  price            :float
#  section_type     :string
#  transfer_type    :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  assistant_id     :bigint(8)
#  bank_id          :bigint(8)
#  country_id       :bigint(8)
#  delegate_id      :bigint(8)
#  manger_id        :bigint(8)
#  marketer_id      :bigint(8)
#
# Indexes
#
#  index_bank_transfers_on_assistant_id  (assistant_id)
#  index_bank_transfers_on_bank_id       (bank_id)
#  index_bank_transfers_on_country_id    (country_id)
#  index_bank_transfers_on_delegate_id   (delegate_id)
#  index_bank_transfers_on_manger_id     (manger_id)
#  index_bank_transfers_on_marketer_id   (marketer_id)
#
# Foreign Keys
#
#  fk_rails_...  (assistant_id => assistants.id)
#  fk_rails_...  (bank_id => banks.id)
#  fk_rails_...  (country_id => countries.id)
#  fk_rails_...  (delegate_id => delegates.id)
#  fk_rails_...  (manger_id => mangers.id)
#  fk_rails_...  (marketer_id => marketers.id)
#

class BankTransfer < ApplicationRecord

  # Associations
  belongs_to :delegate , optional: true
  belongs_to :marketer , optional: true
  belongs_to :assistant , optional: true
  belongs_to :manger, optional: true
  belongs_to :country
  belongs_to :bank


  # Validations
  validates :date_of_transfer,
            :transfer_type,
            :section_type,
            :price,
            presence: true
  validate :not_updatable_fields, on: :update

  # Callbacks
  after_create :update_price_of_employee
  after_update :update_price_of_employee_changes, if: :saved_change_to_price?
  after_update :update_bank_and_manager, if: :saved_change_to_price?
  after_destroy :reverse_operation

  # Scopes
  scope :on_date, -> (date) { where(date_of_transfer: date) }
  scope :between, -> (from, to) { where(date_of_transfer: from..to) }
  scope :delegate, -> (id) { where(delegate_id: id) }
  scope :marketer, -> (id) { where(marketer_id: id) }
  scope :receipt_type, -> { where(transfer_type: 'استلام') }
  
  def update_price_of_employee
    if transfer_type == "ارسال"
      add_price_to_bank_and_manger
      if section_type == "مندوب"
        delegate.update(for_him: delegate.for_him.to_f + price)
      elsif section_type == "مسوق"
        marketer.update(for_him: marketer.for_him.to_f + price)
      elsif section_type == "مساعد"
        assistant.update(for_him: assistant.for_him.to_f + price)
      end
    elsif transfer_type == "استلام"
      remove_price_from_bank_and_manger
      if section_type == "مندوب"
        delegate.update(for_him: delegate.for_him.to_f - price)
      elsif section_type == "مسوق"
        marketer.update(for_him: marketer.for_him.to_f - price)
      elsif section_type == "مساعد"
        assistant.update(for_him: assistant.for_him.to_f - price)
      end
    end
  end


  def reverse_operation
    if transfer_type == "استلام"
      add_price_to_bank_and_manger
      if section_type == "مندوب"
        delegate.update(for_him: delegate.for_him.to_f + price)
      elsif section_type == "مسوق"
        marketer.update(for_him: marketer.for_him.to_f + price)
      elsif section_type == "مساعد"
        assistant.update(for_him: assistant.for_him.to_f + price)
      end
    elsif transfer_type == "ارسال"
      remove_price_from_bank_and_manger
      if section_type == "مندوب"
        delegate.update(for_him: delegate.for_him.to_f - price)
      elsif section_type == "مسوق"
        marketer.update(for_him: marketer.for_him.to_f - price)
      elsif section_type == "مساعد"
        assistant.update(for_him: assistant.for_him.to_f - price)
      end
    end
  end

  def not_updatable_fields
      errors.add(:base,'لا يمكن حفظ البيانات التي قمت بتعديله') and throw(:abort) if not_allowed_changes?
  end

  def not_allowed_changes?
    delegate_id_changed? || marketer_id_changed? || section_type_changed? || transfer_type_changed?
  end

  def update_price_of_employee_changes
    if transfer_type == "ارسال"
      if section_type == "مندوب"
        delegate.update(for_him: delegate.for_him.to_f - price_before_last_save)
        delegate.update(for_him: delegate.for_him.to_f + price)
      elsif section_type == "مسوق"
        marketer.update(for_him: marketer.for_him.to_f - price_before_last_save)
        marketer.update(for_him: marketer.for_him.to_f + price)
      elsif section_type == "مساعد"
        assistant.update(for_him: assistant.for_him.to_f - price_before_last_save)
        assistant.update(for_him: assistant.for_him.to_f + price)
      end
    elsif transfer_type == "استلام"
      if section_type == "مندوب"
        delegate.update(for_him: delegate.for_him.to_f + price_before_last_save)
        delegate.update(for_him: delegate.for_him.to_f - price)
      elsif section_type == "مسوق"
        marketer.update(for_him: marketer.for_him.to_f + price_before_last_save)
        marketer.update(for_him: marketer.for_him.to_f - price)
      elsif section_type == "مساعد"
        assistant.update(for_him: assistant.for_him.to_f + price_before_last_save)
        assistant.update(for_him: assistant.for_him.to_f - price)
      end
    end
  end
  
  def add_price_to_bank_and_manger
    default_manger = Manger.where(country_id: self.country_id).first
    bank.update(balance: bank.balance.to_f + price) if bank.present?
    default_manger.update(to_him: default_manger.to_him.to_f + price)
  end

  def remove_price_from_bank_and_manger
    default_manger = Manger.where(country_id: self.country_id).first
    bank.update(balance: bank.balance.to_f - price) if bank.present?
    default_manger.update(to_him: default_manger.to_him.to_f - price)
  end

  def update_bank_and_manager
    default_manger = Manger.where(country_id: self.country_id).first
    if transfer_type == "ارسال"
      default_manger.update(to_him: default_manger.to_him.to_f - price_before_last_save)
      default_manger.update(to_him: default_manger.to_him.to_f + price)
      bank.update(balance: bank.balance.to_f - price_before_last_save) if bank.present?
      bank.update(balance: bank.balance.to_f + price) if bank.present?
    else
      default_manger.update(to_him: default_manger.to_him.to_f + price_before_last_save)
      default_manger.update(to_him: default_manger.to_him.to_f - price)
      bank.update(balance: bank.balance.to_f + price_before_last_save) if bank.present?
      bank.update(balance: bank.balance.to_f - price) if bank.present?
    end
  end
end

app/controllers/bank_transfers_controller.rb
class BankTransfersController < ApplicationController
  before_action :set_bank_transfer, only: [:show, :edit, :update, :destroy]

  # GET /bank_transfers
  # GET /bank_transfers.json
  def index
    @bank_transfers = \
      if params[:search].present?
        @current_country.bank_transfers.where(
          "
          bank_transfers.transfer_type LIKE :search OR
          bank_transfers.section_type LIKE :search
          ",
          search: "%#{params[:search]}%"
        )
      else
        @current_country.bank_transfers
      end.order(created_at: :desc).page(params[:page])
    
    respond_to do |format|
      format.html
      format.xlsx
      format.pdf do
        render pdf: 'bank_transfers',
               layout: 'pdf'
      end
    end
  end

  # GET /bank_transfers/1
  # GET /bank_transfers/1.json
  def show
  end

  # GET /bank_transfers/new
  def new
    @bank_transfer = @current_country.bank_transfers.new
  end

  # GET /bank_transfers/1/edit
  def edit
  end

  # POST /bank_transfers
  # POST /bank_transfers.json
  def create
    @bank_transfer = @current_country.bank_transfers.new(bank_transfer_params)

    respond_to do |format|
      if @bank_transfer.save
        format.html { redirect_to bank_transfers_url, notice: 'تمت عملية الاضافة بنجاح' }
        format.json { render :show, status: :created, location: @bank_transfer }
      else
        format.html { render :new }
        format.json { render json: @bank_transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_transfers/1
  # PATCH/PUT /bank_transfers/1.json
  def update
    respond_to do |format|
      if @bank_transfer.update(bank_transfer_update_params)
        format.html { redirect_to bank_transfers_url, notice: 'تمت عملية التعديل بنجاح' }
        format.json { render :show, status: :ok, location: @bank_transfer }
      else
        format.html { render :edit }
        format.json { render json: @bank_transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_transfers/1
  # DELETE /bank_transfers/1.json
  def destroy
    @bank_transfer.destroy
    respond_to do |format|
      format.html { redirect_to bank_transfers_url, notice: 'تمت عملية الحذف بنجاح' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_transfer
      @bank_transfer = BankTransfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_transfer_params
      if params[:bank_transfer][:section_type] == "مندوب"
         params.require(:bank_transfer).permit(:date_of_transfer, :transfer_type, :section_type, :delegate_id, :price, :note, :bank_id)
      elsif params[:bank_transfer][:section_type] == "مسوق"
         params.require(:bank_transfer).permit(:date_of_transfer, :transfer_type, :section_type, :marketer_id, :price, :note, :bank_id)
      else 
         params.require(:bank_transfer).permit(:date_of_transfer, :transfer_type, :section_type, :assistant_id, :price, :note, :bank_id)
      end
    end

    def bank_transfer_update_params
      params.require(:bank_transfer).permit(:date_of_transfer, :price, :note)      
    end 
end

app/helpers/bank_transfers_helper.rb
module BankTransfersHelper
end

app/views/bank_transfers/_form.html.erb
<div  class="form-group">
  <%= form_with(model: bank_transfer, local: true) do |form| %>
      <% if bank_transfer.errors.any? %>
        <div class="alert alert-warning" role="alert" style="text-align: center;">
          <h3> يرجئ التاكد من التالي </h3>
          <ul style="list-style-type: none;">
            <% bank_transfer.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <div class="form-group ">
      <%= form.label "حدد تاريخ الحواله", style: "text-align: right; float: right" %>
      <%= form.date_field :date_of_transfer, class: "form-control", placeholder: "تاريخ الحواله"%>
    </div>

    <div class="form-group">
      <%= form.label "حدد نوع الحواله", style: "text-align: right; float: right"%>
      <%= form.select(:transfer_type, options_for_select(["ارسال","استلام"]), {:"data-style" => "form-control", multiple: true}, {class: "form-control", title: "اختر نوع الحواله"})  %>
    </div>

    <div class="form-group">
      <%= form.label "حدد نوع الموظف", style: "text-align: right; float: right"%>
      <%= form.select(:section_type, options_for_select(["مندوب","مسوق","مساعد"]), {:"data-style" => "form-control", multiple: true}, {class: "form-control", title: "نوع الموضف", id:"type", onchange: "myfunction()"})  %>
    </div>

    <div class="form-group", id ="delegate", style="display: block">
      <%= form.label "حدد المندوب", style: "text-align: right; float: right"%>
      <%= form.collection_select(:delegate_id, @current_country.delegates, :id, :name, {:"data-style" => "selectpicker", multiple: true}, {class: "form-control", title: "المندوب"})  %>
    </div>

    <div class="form-group", id="marketer", style="display: none">
      <%= form.label "حدد المسوق", style: "text-align: right; float: right"%>
      <%= form.collection_select(:marketer_id, @current_country.marketers, :id, :name, {:"data-style" => "selectpicker", multiple: true}, {class: "form-control", title: "المسوق"})  %>
    </div>

    <div class="form-group", id="assistant", style="display: none">
      <%= form.label "حدد المساعد", style: "text-align: right; float: right"%>
      <%= form.collection_select(:assistant_id, @current_country.assistants, :id, :name, {:"data-style" => "selectpicker", multiple: true}, {class: "form-control", title: "المساعد"})  %>
    </div>

    <div class="form-group">
      <%= form.label "اسم البنك", style: "text-align: right; float: right"%>
      <%= form.collection_select(:bank_id, @current_country.banks, :id, :name, {:"data-style" => "selectpicker", multiple: true}, {class: "form-control", title: "البنك"})  %>
    </div>

    <div class="form-group">
      <%= form.label "حدد المبلغ ",style: "text-align: right; float: right"%>
      <%= form.number_field :price, step: :any, class: "form-control", placeholder: 'المبلغ المحول' %>
    </div>

    <div class="form-group">
      <%= form.label "ملاحظه",style: "text-align: right; float: right"%>
      <%= form.text_field :note, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.submit "موافق",class:"btn btn btn-secondary my-2 my-sm-0" %>
    </div>
  <% end %>
</div>
<script type="text/javascript">

  function myfunction() {
    var type = document.getElementById("type")
    var delegate = document.getElementById("delegate")
    var marketer = document.getElementById("marketer")
    var assistant = document.getElementById("assistant")
    switch(type.value) {
      case "مندوب":
        delegate.style.display="block"
        marketer.style.display="none"
        assistant.style.display="none"
        break;
      case "مسوق":
        delegate.style.display="none"
        marketer.style.display="block"
        assistant.style.display="none"
        break;
      case "مساعد":
        delegate.style.display="none"
        marketer.style.display="none"
        assistant.style.display="block"
        break;
       }

  }

</script>

app/views/bank_transfers/edit.html.erb
<br>
<h2 style="text-align: center;">تعديل  الحواله</h2>
<div class="alert alert-info" role="alert" style="text-align: center;">
  لا يمكن تعديل ( المندوب - المسوق - المساعد - نوع الموظف - البنك - نوع الحواله )
</div>
<%= render 'form', bank_transfer: @bank_transfer %>

app/views/bank_transfers/index.html.erb
<br>

<h2 style="text-align: center;">
   التحويلات ب<%= @current_country.name %> 
</h2>
<div class="table-responsive" >
  <table class="table">
    <thead class="thead-light" style="text-align: center;">
      <tr>
        <th>تاريخ الحواله</th>
        <th>نوع الحواله</th>
        <th>صنف المحول</th>
        <th>الاسم</th>
        <th>المبلغ</th>
        <th>اسم البنك</th>
        <th>ملاحظه</th>
        <th colspan="2">
          <%= form_tag(bank_transfers_path, :method => "get", class: 'navbar-form navbar-left') do %>
                <div class="input-group">
                  <%= search_field_tag :search, params[:search], placeholder: "البحث", class: "form-control" %>
                  <div class="input-group-btn">
                    <button type="submit" class="btn btn btn-secondary my-2 my-sm-0"><span class="glyphicon glyphicon-search"></span> بحث</button>
                  </div>
                </div>
          <% end %>
        </th>
      </tr>
    </thead>

    <tbody style="text-align: center;">
      <% @bank_transfers.each do |bank_transfer| %>
        <tr>
          <td><%= bank_transfer.date_of_transfer.to_date %></td>
          <td><%= bank_transfer.transfer_type %></td>
          <td><%= bank_transfer.section_type %></td>
          <td><%= bank_transfer.manger&.name || bank_transfer.delegate&.name || bank_transfer.marketer&.name || bank_transfer.assistant&.name %></td>
          <td><%= bank_transfer.price %></td>
          <td><%= bank_transfer.bank&.name %></td>
          <td><%= bank_transfer.note %></td>
          <td style="text-align: center;"><%= link_to 'تعديل', edit_bank_transfer_path(bank_transfer),class: "btn btn-light" %></td>
          <td style="text-align: center;"><%= link_to 'حذف', bank_transfer, method: :delete, class: "btn btn-light", data: { confirm: 'هل انت متاكد؟' }%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'إضافة حواله', new_bank_transfer_path ,class:"btn btn btn-secondary my-2 my-sm-0" %>
<%= link_to "استخراج ملف pdf", bank_transfers_path(format: "pdf"),class: "btn btn btn-secondary my-2 my-sm-0" %>
<%= link_to 'عرض التقرير ', reports_transfers_report_path, class: "btn btn btn-secondary my-2 my-sm-0"%>

app/views/bank_transfers/index.pdf.erb
<br>

<h2 style="text-align: center;">
   التحويلات ب<%= @current_country.name %> 
</h2>
<div class="table-responsive" >
  <table class="table">
    <thead class="thead-light" style="text-align: center;">
      <tr>
        <th>تاريخ الحواله</th>
        <th>نوع الحواله</th>
        <th>صنف المحول</th>
        <th>الاسم</th>
        <th>المبلغ</th>
        <th>ملاحظه</th>
    </thead>

    <tbody style="text-align: center;">
      <% @current_country.bank_transfers.each do |bank_transfer| %>
        <tr>
          <td><%= bank_transfer.date_of_transfer.to_date %></td>
          <td><%= bank_transfer.transfer_type %></td>
          <td><%= bank_transfer.section_type %></td>
          <td><%= bank_transfer.manger&.name || bank_transfer.delegate&.name || bank_transfer.marketer&.name || bank_transfer.assistant&.name %></td>
          <td><%= bank_transfer.price %></td>
          <td><%= bank_transfer.note %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bank_transfers/new.html.erb
<br>
<h2 style="text-align: center;" >إضافة حوالة </h2>

<%= render 'form', bank_transfer: @bank_transfer %>