config/routes.rb
Rails.application.routes.draw do
  resources :banks
  get 'reports/sales_report'
  get 'reports/transfers_report'
  resources :product_discounts
  resources :manger_discounts
  get 'session/login'
  post 'session/attempt_login'
  get 'session/logout'
  resources :bank_transfers
  resources :sales_operations do
    collection do
      post :import
    end
  end
  resources :mangers
  resources :assistants
  resources :external_employees
  resources :external_transfers
  resources :marketers
  resources :deliveries
  resources :delegates
  resource  :home,                      only: [:index]
  root 'home#index'
  resources :users, except: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/manger_discount.rb
# == Schema Information
#
# Table name: manger_discounts
#
#  id               :bigint(8)        not null, primary key
#  Desc             :string
#  date_of_discount :date
#  value            :float
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  country_id       :bigint(8)
#  manger_id        :bigint(8)
#  bank_id        :bigint(8)
#
# Indexes
#
#  index_manger_discounts_on_country_id  (country_id)
#  index_manger_discounts_on_manger_id   (manger_id)
#
# Foreign Keys
#
#  fk_rails_...  (country_id => countries.id)
#  fk_rails_...  (manger_id => mangers.id)
#

class MangerDiscount < ApplicationRecord
  # Associations
  belongs_to :manger
  belongs_to :country
  belongs_to :bank


  # Validations
  validates :value,
            :date_of_discount,
             presence: true

  # Callbacks
  after_create :update_manger_and_bank_account
  after_update :update_manger_and_bank_account_changes, if: :saved_change_to_value?
  after_destroy :reverse_changes

  def update_manger_and_bank_account
    manger.update(for_him: manger.for_him.to_f - value)
    manger.update(to_him: manger.to_him.to_f - value)
    manger.update(final_manager_amount: manger.final_manager_amount.to_f - value)
    bank.update(balance: bank.balance.to_f - value) if bank.present?
  end

  def update_manger_and_bank_account_changes
    manger.update(for_him: manger.for_him.to_f + value_before_last_save)
    manger.update(to_him: manger.to_him.to_f + value_before_last_save)
    manger.update(final_manager_amount: manger.final_manager_amount.to_f + value_before_last_save)
    bank.update(balance: bank.balance.to_f + value_before_last_save) if bank.present?
    manger.update(for_him: manger.for_him.to_f - value)
    manger.update(to_him: manger.to_him.to_f - value)
    manger.update(final_manager_amount: manger.final_manager_amount.to_f - value)
    bank.update(balance: bank.balance.to_f - value) if bank.present?
  end

  def reverse_changes
    manger.update(for_him: manger.for_him.to_f + value)
    manger.update(to_him: manger.to_him.to_f + value)
    manger.update(final_manager_amount: manger.final_manager_amount.to_f + value)
    bank.update(balance: bank.balance.to_f + value) if bank.present?
  end
end

app/controllers/manger_discounts_controller.rb
class MangerDiscountsController < ApplicationController
  before_action :set_manger, only: [:create]
  before_action :set_manger_discount, only: [:show, :edit, :update, :destroy]

  # GET /manger_discounts
  # GET /manger_discounts.json
  def index
    @manger_discounts = @current_country.manger_discounts.page(params[:page])
    
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'Manger Discount',
               layout: 'pdf'
      end
    end
  end

  # GET /manger_discounts/1
  # GET /manger_discounts/1.json
  def show
  end

  # GET /manger_discounts/new
  def new
    @manger_discount = @current_country.manger_discounts.new
  end

  # GET /manger_discounts/1/edit
  def edit
  end

  # POST /manger_discounts
  # POST /manger_discounts.json
  def create
    @manger_discount = @current_country.manger_discounts.new(manger_discount_params)

    respond_to do |format|
      if @manger_discount.save
        format.html { redirect_to manger_discounts_url, notice: 'تمت عملية الاضافة بنجاح' }
        format.json { render :show, status: :created, location: @manger_discount }
      else
        format.html { render :new }
        format.json { render json: @manger_discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manger_discounts/1
  # PATCH/PUT /manger_discounts/1.json
  def update
    respond_to do |format|
      if @manger_discount.update(manger_discount_params)
        format.html { redirect_to manger_discounts_url, notice: 'تمت عملية التعديل بنجاح' }
        format.json { render :show, status: :ok, location: @manger_discount }
      else
        format.html { render :edit }
        format.json { render json: @manger_discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manger_discounts/1
  # DELETE /manger_discounts/1.json
  def destroy
    @manger_discount.destroy
    respond_to do |format|
      format.html { redirect_to manger_discounts_url, notice: 'تمت عملية الحذف بنجاح' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manger_discount
      @manger_discount = MangerDiscount.find(params[:id])
    end

    def set_manger
      params[:manger_discount][:manger_id] = @current_country.mangers.first.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manger_discount_params
      params.require(:manger_discount).permit(:manger_id, :Desc, :value, :date_of_discount, :bank_id)
    end    
end

app/helpers/manger_discounts_helper.rb
module MangerDiscountsHelper
end

app/views/manger_discounts/_form.html.erb
<div  class="form-group">
  <%= form_with(model: manger_discount, local: true) do |form| %>
      <% if manger_discount.errors.any? %>
        <div class="alert alert-warning" role="alert" style="text-align: center;">
          <h3> يرجئ التاكد من التالي </h3>
          <ul style="list-style-type: none;">
            <% manger_discount.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <div class="form-group">
      <%= form.label 'السبب', style: "text-align: right; float: right" %>
      <%= form.text_field :Desc, class: "form-control", placeholder: 'السبب' %>
    </div>

    <div class="form-group">
      <%= form.label 'المبلغ المصروف', style: "text-align: right; float: right" %>
      <%= form.number_field :value, step: :any, class: "form-control", placeholder: 'المبلغ' %>
    </div>
    <div class="form-group ">
      <%= form.label 'تاريخ صرف المبلغ', style: "text-align: right; float: right" %>
      <%= form.date_field :date_of_discount, class: "form-control", placeholder: "تاريخ الصرف"%>
    </div>

    <div class="form-group">
      <%= form.label "اسم البنك", style: "text-align: right; float: right"%>
      <%= form.collection_select(:bank_id, @current_country.banks, :id, :name, {:"data-style" => "selectpicker", multiple: true}, {class: "form-control", title: "البنك"})  %>
    </div>

    <div class="actions">
      <%= form.submit "موافق",class:"btn btn btn-secondary my-2 my-sm-0" %>
    </div>
  <% end %>
</div>

app/views/manger_discounts/edit.html.erb
<br>
<h2 style="text-align: center;">تعديل  مصروف المدير</h2>
<div class="alert alert-info" role="alert" style="text-align: center;">
  لا يمكن تعديل البنك 
</div>

<%= render 'form', manger_discount: @manger_discount %>

app/views/manger_discounts/index.html.erb
<br>
<p id="notice"  style="text-align: center;" ><%= notice %></p>

<h2 style="text-align: center;">
مصروفات المدير ب<%= @current_country.name %> 
</h2>
<div class="table-responsive" >
  <table class="table">
    <thead class="thead-light" style="text-align: right;">
      <tr>
        <th>سبب صرف المبلغ</th>
        <th>المبلغ</th>
        <th>تاريخ الصرف</th>
        <th>اسم البنك</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody style="text-align: right;">
      <% @manger_discounts.each do |manger_discount| %>
        <tr>
          <td><%= manger_discount.Desc %></td>
          <td><%= manger_discount.value %></td>
          <td><%= manger_discount.date_of_discount %></td>
          <td><%= manger_discount.bank&.name %></td>
          <td><%= link_to 'تعديل', edit_manger_discount_path(manger_discount), class: "btn btn-light" %></td>
          <td><%= link_to 'حذف', manger_discount, method: :delete, class:"btn btn-light", data: { confirm:'هل انت متاكد؟' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'إضافة مصروف', new_manger_discount_path , class: "btn btn btn-secondary my-2 my-sm-0" %>
<%= link_to "استخراج ملف pdf", manger_discounts_path(format: "pdf"),class: "btn btn btn-secondary my-2 my-sm-0" %>

app/views/manger_discounts/index.pdf.erb
<br>
<h2 style="text-align: center;">
مصروفات المدير ب<%= @current_country.name %> 
</h2>
<br>

<div class="table-responsive" >
  <table class="table">
    <thead class="thead-light" style="text-align: right;">
      <tr>
        <th>سبب صرف المبلغ</th>
        <th>المبلغ</th>
        <th>تاريخ الصرف</th>
        <th>اسم البنك</th>
      </tr>
    </thead>

    <tbody style="text-align: right;">
      <% @current_country.manger_discounts.each do |manger_discount| %>
        <tr>
          <td><%= manger_discount.Desc %></td>
          <td><%= manger_discount.value %></td>
          <td><%= manger_discount.date_of_discount %></td>
          <td><%= manger_discount.bank&.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/manger_discounts/new.html.erb
<br>
<h2 style="text-align: center;" >إضافة مصروف مدير </h2>

<%= render 'form', manger_discount: @manger_discount %>

app/views/manger_discounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manger:</strong>
  <%= @manger_discount.manger %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @manger_discount.Desc %>
</p>

<p>
  <strong>Value:</strong>
  <%= @manger_discount.value %>
</p>

<%= link_to 'Edit', edit_manger_discount_path(@manger_discount) %> |
<%= link_to 'Back', manger_discounts_path %>