config/routes.rb
Rails.application.routes.draw do
  resources :banks
  get 'reports/sales_report'
  get 'reports/transfers_report'
  resources :product_discounts
  resources :manger_discounts
  get 'session/login'
  post 'session/attempt_login'
  get 'session/logout'
  resources :bank_transfers
  resources :sales_operations do
    collection do
      post :import
    end
  end
  resources :mangers
  resources :assistants
  resources :external_employees
  resources :external_transfers
  resources :marketers
  resources :deliveries
  resources :delegates
  resource  :home,                      only: [:index]
  root 'home#index'
  resources :users, except: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  skip_before_action :authrized
  def sales_report
    @sales_operations = \
      if params[:from].present? && params[:to].present? && params[:marketer_id].try(:[],:id).present? && params[:delegate_id].try(:[],:id).present?
        @current_country.sales_operations.between(params[:from], params[:to]).delegate(params[:delegate_id][:id]).marketer(params[:marketer_id][:id])
      elsif params[:from].present? && params[:to].present? && params[:delegate_id].try(:[],:id).present?
        @current_country.sales_operations.between(params[:from], params[:to]).delegate(params[:delegate_id][:id])
      elsif params[:from].present? && params[:to].present? && params[:marketer_id].try(:[],:id).present?
        @current_country.sales_operations.between(params[:from], params[:to]).marketer(params[:marketer_id][:id])
      elsif params[:marketer_id].try(:[],:id).present? && params[:delegate_id].try(:[],:id).present?
        @current_country.sales_operations.where(date: Date.today).delegate(params[:delegate_id][:id]).marketer(params[:marketer_id][:id])
      elsif params[:delegate_id].try(:[],:id).present?
        @current_country.sales_operations.where(date: Date.today).delegate(params[:delegate_id][:id])
      elsif params[:marketer_id].try(:[],:id).present?
        @current_country.sales_operations.where(date: Date.today).marketer(params[:marketer_id][:id])
      elsif params[:from].present? && params[:to].present?
        @current_country.sales_operations.between(params[:from], params[:to])
      else
        @current_country.sales_operations.where(date: Date.today)
      end
    respond_to do |format|
      format.html
      format.xlsx
      format.pdf do
        render pdf: 'sales_operations',
               layout: 'pdf'
      end
    end
  end

  def transfers_report
    @bank_transfers = \
      if params[:from].present? && params[:to].present? && params[:marketer_id].try(:[],:id).present? && params[:delegate_id].try(:[],:id).present?
        @current_country.bank_transfers.between(params[:from], params[:to]).delegate(params[:delegate_id][:id]).marketer(params[:marketer_id][:id])
      elsif params[:from].present? && params[:to].present? && params[:delegate_id].try(:[],:id).present?
        @current_country.bank_transfers.between(params[:from], params[:to]).delegate(params[:delegate_id][:id])
      elsif params[:from].present? && params[:to].present? && params[:marketer_id].try(:[],:id).present?
        @current_country.bank_transfers.between(params[:from], params[:to]).marketer(params[:marketer_id][:id])
      elsif params[:marketer_id].try(:[],:id).present? && params[:delegate_id].try(:[],:id).present?
        @current_country.bank_transfers.on_date(Date.today).delegate(params[:delegate_id][:id]).marketer(params[:marketer_id][:id])
      elsif params[:delegate_id].try(:[],:id).present?
        @current_country.bank_transfers.on_date(Date.today).delegate(params[:delegate_id][:id])
      elsif params[:marketer_id].try(:[],:id).present?
        @current_country.bank_transfers.on_date(Date.today).marketer(params[:marketer_id][:id])
      elsif params[:from].present? && params[:to].present?
        @current_country.bank_transfers.between(params[:from], params[:to])
      else
        @current_country.bank_transfers.on_date(Date.today)
      end
    respond_to do |format|
      format.html
      format.xlsx
      format.pdf do
        render pdf: 'transfers_report',
               layout: 'pdf'
      end
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/sales_report.html.erb
<br>
<div class="alert alert-info" role="alert" style="text-align: center;">
  سوف يتم عرض مبيعات تاريخ اليوم اذا لم يتم تحديد التاريخ
</div>

<div>
      <%= form_tag(reports_sales_report_path, :method => "get", class: 'navbar-form navbar-left') do %>
        <div class="input-group">
          <%= date_field_tag :from, params[:from], placeholder: "من تاريخ", class: "form-control" %>
          <%= date_field_tag :to, params[:to], placeholder: "الى تاريخ", class: "form-control" %>
          <%= collection_select :delegate_id, :id, @current_country.delegates, :id, :name,{:"data-style" => "selectpicker", multiple: true, include_blank: true}, {class: "form-control", title: "المندوب"} %>
          <%= collection_select :marketer_id, :id, @current_country.marketers, :id, :name,{:"data-style" => "selectpicker", multiple: true, include_blank: true}, {class: "form-control", title: "المسوق"} %>
          <div class="input-group-btn">
            <button type="submit" class="btn btn btn-secondary my-2 my-sm-0"><span class="glyphicon glyphicon-search"></span> بحث</button>
          </div>
        </div>
      <% end %>
</div>
<br>
<br>
<h4 style="text-align: center;"><%= @sales_operations.blank? ? "لا توجد عمليات بيع " : " ب#{@current_country.name }  تقرير عمليات البيع" %></h4>
<p style="text-align: center;">
  <%= params[:delegate_id].try(:[],:id).present? ? " المندوب #{Delegate.find(params[:delegate_id][:id]).name.to_s}  " : "" %>
  <%= params[:delegate_id].try(:[],:id).present? ? " اجمالي المبلغ المستحق  : #{@sales_operations.map(&:delegate_commission).sum.to_s}" : "" %>
</p>
<p style="text-align: center;">
  <%= params[:marketer_id].try(:[],:id).present? ? " المسوق #{Marketer.find(params[:marketer_id][:id]).name.to_s}  " : "" %>
  <%= params[:marketer_id].try(:[],:id).present? ? " اجمالي المبلغ المستحق  : #{@sales_operations.map(&:marketer_commission).sum.to_s}" : "" %>
</p>
<div class="table-responsive" >
  <table class="table">
    <thead class="thead-light" style="text-align: center;">
      <tr>
        <th>التاريخ</th>
        <th>السعر</th>
        <th>منطقة العميل</th>
        <th colspan="4">رقم العميل</th>
      </tr>
    </thead>

    <tbody style="text-align: right;">
      <% @sales_operations.each do |sales_operation| %>
        <tr>
          <td><%= sales_operation.date.to_date %></td>
          <td><%= sales_operation.price %></td>
          <td><%= sales_operation.customr_city %></td>
          <td colspan='4' style="color: <%= SalesOperation.where(country_id: @current_country.id).where.not(id: sales_operation.id).find_by_customr_no(sales_operation.customr_no).present? ? 'red' : 'black' %>">
            <%= sales_operation.customr_no %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot  style="text-align: right;">
        <tr>
          <td>المجموع</td>
          <td>الا جمالي السابق</td>
          <td>اجمالي الخصومات</td>
          <td>الاجمالي</td>
          <td>عدد الجوالين</td>
          <td>عدد العلب</td>
          <td>عدد الطلبات</td>
        </tr>
        <tr>
          <td>
            <%= @sales_operations.pluck(:manager_commission).sum  %>
          </td>
          <td>
            <%= @sales_operations.first&.manger&.for_him.to_f - @sales_operations.pluck(:manager_commission).sum  %>
          </td>
          <td>
            <%= BankTransfer.where(country_id: @current_country.id).
                             on_date(Date.today).
                             receipt_type.
                             pluck(:price).sum  %>
          </td>
          <td>
            <%= @sales_operations.first&.manger&.for_him.to_f %>
          </td>
          <td><%= @sales_operations.pluck(:gallon_amount).sum  %></td>
          <td><%= @sales_operations.pluck(:box_amount).sum %></td>
          <td><%= @sales_operations.count %></td>
        </tr>
    </tfoot>
  </table>
</div>
<%= link_to ' استخراج اكسل',"/reports/sales_report.xlsx?from=#{params[:from]}&to=#{params[:to]}&delegate_id%5Bid%5D=#{params[:delegate_id].try(:[],:id)}&marketer_id%5Bid%5D=#{params[:marketer_id].try(:[],:id)}",class: "btn btn btn-secondary my-2 my-sm-0" %>
<%= link_to 'استخراج pdf',"/reports/sales_report.pdf?from=#{params[:from]}&to=#{params[:to]}&delegate_id%5Bid%5D=#{params[:delegate_id].try(:[],:id)}&marketer_id%5Bid%5D=#{params[:marketer_id].try(:[],:id)}",class: "btn btn btn-secondary my-2 my-sm-0" %>

app/views/reports/sales_report.pdf.erb
<h2 style="text-align: center;">
تقرير عمليات البيع ب<%= @current_country.name %> 
</h2>
<p style="text-align: center;"><%= params[:delegate_id].try(:[],:id).present? ? " المندوب #{Delegate.find(params[:delegate_id][:id]).name.to_s}" : "" %></p>
<p style="text-align: center;"><%= params[:marketer_id].try(:[],:id).present? ? " المسوق #{Marketer.find(params[:marketer_id][:id]).name.to_s}" : "" %></p>
<div class="table" >
  <table class="table">
    <thead class="thead-light" style="text-align: center;">
      <tr>
        <th>التاريخ</th>
        <th>السعر</th>
        <th>منطقة العميل</th>
        <th colspan='4'>رقم العميل</th>
      </tr>
    </thead>
    <tbody style="text-align: center;">
      <% @sales_operations.each do |sales_operation| %>
        <tr>
          <td><%= sales_operation.date.to_date %></td>
          <td><%= sales_operation.price %></td>
          <td><%= sales_operation.customr_city %></td>
          <td colspan='4' style="color: <%= SalesOperation.where(country_id: @current_country.id).where.not(id: sales_operation.id).find_by_customr_no(sales_operation.customr_no).present? ? 'red' : 'black' %>">
            <%= sales_operation.customr_no %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot  style="text-align: center;">
        <tr>
          <td>المجموع</td>
          <td>الا جمالي السابق</td>
          <td>اجمالي الخصومات</td>
          <td>الاجمالي</td>
          <td>عدد الجوالين</td>
          <td>عدد العلب</td>
          <td>عدد الطلبات</td>
        </tr>
        <tr>
          <td>
            <%= @sales_operations.pluck(:manager_commission).sum  %>
          </td>
          <td>
            <%= @sales_operations.first&.manger&.for_him.to_f - @sales_operations.pluck(:manager_commission).sum  %>
          </td>
          <td>
            <%= BankTransfer.where(country_id: @current_country.id).
                             on_date(Date.today).
                             receipt_type.
                             pluck(:price).sum  %>
          </td>
          <td>
            <%= @sales_operations.first&.manger&.for_him.to_f %>
          </td>
          <td><%= @sales_operations.pluck(:gallon_amount).sum  %></td>
          <td><%= @sales_operations.pluck(:box_amount).sum %></td>
          <td><%= @sales_operations.count %></td>
        </tr>
    </tfoot>
  </table>
</div>

app/views/reports/transfers_report.html.erb
<br>
<div class="alert alert-info" role="alert" style="text-align: center;">
  سوف يتم عرض حوالات تاريخ اليوم اذا لم يتم تحديد التاريخ
</div>
<div>
      <%= form_tag(reports_transfers_report_path, :method => "get", class: 'navbar-form navbar-left') do %>
        <div class="input-group">
          <%= date_field_tag :from, params[:from], placeholder: "من تاريخ", class: "form-control" %>
          <%= date_field_tag :to, params[:to], placeholder: "الى تاريخ", class: "form-control" %>
          <%= collection_select :delegate_id, :id, @current_country.delegates, :id, :name,{:"data-style" => "selectpicker", multiple: true, include_blank: true}, {class: "form-control", title: "المندوب"} %>
          <%= collection_select :marketer_id, :id, @current_country.marketers, :id, :name,{:"data-style" => "selectpicker", multiple: true, include_blank: true}, {class: "form-control", title: "المسوق"} %>
          <div class="input-group-btn">
            <button type="submit" class="btn btn btn-secondary my-2 my-sm-0"><span class="glyphicon glyphicon-search"></span> بحث</button>
          </div>
        </div>
      <% end %>
</div>
<br>
<br>
<h4 style="text-align: center;"><%= @bank_transfers.blank? ? "لا توجد حوالات" : " تقرير الحوالات ب#{@current_country.name }" %></h4>
<p style="text-align: center;">
  <%= params[:delegate_id].try(:[],:id).present? ? " المندوب #{Delegate.find(params[:delegate_id][:id]).name.to_s}  " : "" %>
</p>
<p style="text-align: center;">
  <%= params[:marketer_id].try(:[],:id).present? ? " المسوق #{Marketer.find(params[:marketer_id][:id]).name.to_s}  " : "" %>
</p>
<div class="table-responsive" >
  <table class="table">
    <thead class="thead-light" style="text-align: center;">
      <tr>
        <th>تاريخ الحواله</th>
        <th>نوع الحواله</th>
        <th>صنف المحول</th>
        <th>الاسم</th>
        <th>المبلغ</th>
        <th>اسم البنك</th>
        <th>ملاحظه</th>
        <th colspan="2">
          <%= form_tag(bank_transfers_path, :method => "get", class: 'navbar-form navbar-left') do %>
                <div class="input-group">
                  <%= search_field_tag :search, params[:search], placeholder: "البحث", class: "form-control" %>
                  <div class="input-group-btn">
                    <button type="submit" class="btn btn btn-secondary my-2 my-sm-0"><span class="glyphicon glyphicon-search"></span> بحث</button>
                  </div>
                </div>
          <% end %>
        </th>
      </tr>
    </thead>

    <tbody style="text-align: center;">
      <% @bank_transfers.each do |bank_transfer| %>
        <tr>
          <td><%= bank_transfer.date_of_transfer.to_date %></td>
          <td><%= bank_transfer.transfer_type %></td>
          <td><%= bank_transfer.section_type %></td>
          <td><%= bank_transfer.manger&.name || bank_transfer.delegate&.name || bank_transfer.marketer&.name || bank_transfer.assistant&.name %></td>
          <td><%= bank_transfer.price %></td>
          <td><%= bank_transfer.bank&.name %></td>
          <td><%= bank_transfer.note %></td>
          <td style="text-align: center;"><%= link_to 'تعديل', edit_bank_transfer_path(bank_transfer),class: "btn btn-light" %></td>
          <td style="text-align: center;"><%= link_to 'حذف', bank_transfer, method: :delete, class: "btn btn-light", data: { confirm: 'هل انت متاكد؟' }%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'استخراج pdf',"/reports/transfers_report.pdf?from=#{params[:from]}&to=#{params[:to]}&delegate_id%5Bid%5D=#{params[:delegate_id].try(:[],:id)}&marketer_id%5Bid%5D=#{params[:marketer_id].try(:[],:id)}",class: "btn btn btn-secondary my-2 my-sm-0" %>

app/views/reports/transfers_report.pdf.erb
<h2 style="text-align: center;">
تقرير الحوالات ب<%= @current_country.name %> 
</h2>
<p style="text-align: center;"><%= params[:delegate_id].try(:[],:id).present? ? " المندوب #{Delegate.find(params[:delegate_id][:id]).name.to_s}" : "" %></p>
<p style="text-align: center;"><%= params[:marketer_id].try(:[],:id).present? ? " المسوق #{Marketer.find(params[:marketer_id][:id]).name.to_s}" : "" %></p>
<div class="table" >
<table class="table">
    <thead class="thead-light" style="text-align: center;">
      <tr>
        <th>تاريخ الحواله</th>
        <th>نوع الحواله</th>
        <th>صنف المحول</th>
        <th>الاسم</th>
        <th>المبلغ</th>
        <th>اسم البنك</th>
        <th>ملاحظه</th>
    </thead>

    <tbody style="text-align: center;">
      <% @current_country.bank_transfers.each do |bank_transfer| %>
        <tr>
          <td><%= bank_transfer.date_of_transfer.to_date %></td>
          <td><%= bank_transfer.transfer_type %></td>
          <td><%= bank_transfer.section_type %></td>
          <td><%= bank_transfer.manger&.name || bank_transfer.delegate&.name || bank_transfer.marketer&.name || bank_transfer.assistant&.name %></td>
          <td><%= bank_transfer.price %></td>
          <td><%= bank_transfer.bank&.name %></td>
          <td><%= bank_transfer.note %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>